### PR TITLE
Feature/maintenance

### PR DESCRIPTION
**Pull request by funkenstrahlen**

### CODE REVIEW

**Comment by flovilmart** [comment]
The tests are still not passing on CI. Also, can you please not merge without review?

**Comment by flovilmart** [comment]
@funkenstrahlen?

**Comment by flovilmart** [comment]
@funkenstrahlen i removed your write access as you merged without checking the CI, and pushed directly to master. I hoped I didn’t need to put all protections in place. Now the tag you published is deleted and i’ll Revert the master branch to before this Pr.

**Comment by funkenstrahlen** [comment]
@flovilmart I am sorry. I have been very busy in the last days and did not find time to reply.

I understand it was wrong to directly push to master. I misunderstood you adding me with push access as a request to push directly. We should have communicated better how to work together.

It is ok you reverted all changes for now. However I believe the changes are a valid and good improvement.

I tried to fix the new failing test but I can not find the issue. It only fails on Travis. It perfectly runs locally. This is perhaps due to a different image magick version?

**Comment by flovilmart** [comment]
Well, this should be sorted out before merging in any case. I added you with the right to write in order to be able to merge if test pass, not if they failed.

**Comment by funkenstrahlen** [comment]
Yes you are right. This was not correctly done from my side.

**Pull request merged**
